version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: splitwise_prod
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/splitwise_prod
      SECRET_KEY_BASE: super_secret_key_base_please_change
      PORT: 8080
      MIX_ENV: prod
      PHX_SERVER: "true"
    ports:
      - "8080:8080"
    restart: on-failure
    stdin_open: true
    tty: true
    entrypoint: ["/opt/app/deploy/run-server.sh"]

volumes:
  db_data:
